CONFIG_CAN=y
CONFIG_ISOTP=y
CONFIG_LOG=y
CONFIG_REBOOT=y

# Empfohlen für Multi-Frame UDS Handling
CONFIG_ISOTP_RX_BUF_COUNT=4

CONFIG_UDS_SERVER=y
CONFIG_ENTROPY_GENERATOR=y
CONFIG_UDS_SEC_MAX_FAILED_ATTEMPTS=5
CONFIG_UDS_SEC_LOCKOUT_TIME_MS=30000
